version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:

  build_ui:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - run:
          name: setup
          command: 'sudo npm i -g npm'
      - restore_cache:
          keys:
            - ui-npm-{{ .Branch }}-{{ checksum "web/package-lock.json" }}
            - ui-npm-{{ .Branch }}-
            - ui-npm-

      - run:
          name: ui-npm-audit
          command: 'cd web && npm audit'
      - run:
          name: ui-npm-install
          command: 'cd web && npm i'

      - save_cache:
          key: ui-npm-{{ .Branch }}-{{ checksum "web/package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: ui-npm-test
          command: 'cd web && npm t'

  build_pp:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          keys:
            - pp-mvn-{{ .Branch }}-{{ checksum "api/plotpoints/pom.xml" }}
            - pp-mvn-{{ .Branch }}-
            - pp-mvn-

      - run:
          name: pp-mvn-dependencies
          command: 'cd api/plotpoints && mvn dependency:go-offline'

      - save_cache:
          paths:
            - ~/.m2
          key: pp-mvn-{{ .Branch }}-{{ checksum "api/plotpoints/pom.xml" }}

      - run:
          name: pp-mvn-package
          command: 'cd api/plotpoints && mvn package'

      - store_test_results:
          path: api/plotpoints/target/surfire-reports
      - store_artifacts:
          path: api/plotpoints/target/plotpoints.jar

#  test_pp:
#    executor: newman/postman-newman-docker

#    steps:
#      - checkout
#      - newman/newman-run:
#          collection: .postman/plot_router-plot_points-get-all.postman_collection.json

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_ui
      - build_pp
 #     - test_pp:
 #       requires:
 #         - build_pp

  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *" # Run nightly at 0300 + 15
          filters:
            branches:
              only:
                - master
    jobs:
#      - test_pp
      - build_ui
