version: 2.1

jobs:

  build_consumer_ui:
    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - run:
          name: setup
          command: 'sudo npm i -g npm'
      - restore_cache:
          keys:
            - ui-consumer-npm-{{ .Branch }}-{{ checksum "ui/consumer/package-lock.json" }}
            - ui-consumer-npm-{{ .Branch }}-
            - ui-consumer-npm-

      - run:
          name: ui-consumer-npm-audit
          command: 'cd ui/consumer && npm audit'
      - run:
          name: ui-consumer-npm-install
          command: 'cd ui/consumer && npm i'

      - save_cache:
          key: ui-consumer-npm-{{ .Branch }}-{{ checksum "ui/consumer/package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: ui-consumer-npm-test
          command: 'cd ui/consumer && npm t'

      - run:
          name: ui-consumer-npm-build
          command: 'cd ui/consumer && npm run build'
      
      - persist_to_workspace:
          root: ui/consumer
          paths:
            - build/
