version: 2

jobs:

  build_ui:
    working_directory: ~/PlotRouter/web

    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: ui-npm-{{ checksum "package-lock.json" }}

      - run:
          name: ui-npm-audit
          command: npm audit
      - run:
          name: ui-npm-install
          command: npm i

      - save_cache:
          key: ui-npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run:
          name: ui-npm-test
          command: npm t

  build_pp:
    working_directory: ~/PlotRouter/api/plotpoints

    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    steps:
      - checkout
      - restore_cache:
          key: pp-mvn-{{ checksum "pom.xml" }}

      - run:
          name: pp-mvn-dependencies
          command: |
            cd api/plotpoints |
            mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: pp-mvn-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surfire-reports
      - store_artifacts:
          path: target/plotpoints.jar

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_ui
      - build_pp
      - test_pp:
        requires:
          - build_pp

  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *" # Run nightly at 0300 + 15
          filters:
            branches:
              only:
                - master
    jobs:
      - test_pp
      - build_ui
